name: Update with the latest schemes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository code
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Update schemes
        uses: tinted-theming/tinted-builder-rust@latest

      - name: Update themes file
        run: ./scripts/generate_themes_file

      - name: Update skins file
        run: ./scripts/generate_skins_file

      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@ac8823709a85c7ce090849ac3e5fe24d006f6e18 # v5.0.1
        with:
          commit_message: Update with the latest colorschemes
          branch: ${{ github.head_ref }}
          commit_user_name: tinted-theming-bot
          commit_user_email: tintedtheming@proton.me
          commit_author: tinted-theming-bot <tintedtheming@proton.me>
